title: Rural Tech Retreat 2021
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2021_style/img/icon-large.png"

social: 
  name: West Slope Technologists
  link: "https://www.facebook.com/groups/westslopetechnologists"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2021_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/westslopetechnologists
  - title: twitter
    url: https://twitter.com/WestSlopeCOTech/
  - title: slack
    url: https://join.slack.com/t/westslopetech/shared_invite/zt-3wv7wel1-2CGl7OPSB~PR942sfsV~EQ

# Build settings
markdown: kramdown
permalink: pretty